services:
  stats-db:
    image: postgres:16.1
    container_name: ewm-stats-db
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
    ports:
      - "6542:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ewm -d ewm-stats"]
      interval: 5s
      timeout: 5s
      retries: 10

  stats-server:
    build:
      context: .
      dockerfile: ./ewm-stats/ewm-stats-server/Dockerfile
    image: ewm-stats-service:latest
    container_name: ewm-stats
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
    ports:
      - "9090:9090"

  ewm-db:
    image: postgres:16.1
    container_name: ewm-main-db
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
    ports:
      - "6541:5432"
    volumes:
      - ./docker/db-main-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ewm -d ewm-main"]
      interval: 5s
      timeout: 5s
      retries: 10

  ewm-service:
    build:
      context: .
      dockerfile: ./ewm-main-service/Dockerfile
    image: ewm-main-service:latest
    container_name: ewm-main
    depends_on:
      ewm-db:
        condition: service_healthy
      stats-server:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - STATS_SERVER_URL=http://stats-server:9090
    ports:
      - "8080:8080"
